# Generated by Django 5.2.8 on 2025-11-15 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 2020 Toyota Corolla LE", max_length=200
                    ),
                ),
                ("make", models.CharField(db_index=True, max_length=100)),
                ("model", models.CharField(db_index=True, max_length=100)),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1940),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="Price in Nigerian Naira (NGN)",
                        max_digits=12,
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Mileage in kilometers",
                        null=True,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        db_index=True,
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        db_index=True,
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Brand New"),
                            ("foreign_used", "Foreign Used (Tokunbo)"),
                            ("local_used", "Locally Used"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the car"),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sweet_deals", "Sweet Deals"),
                            ("latest_listings", "Latest Listings"),
                            ("featured", "Featured"),
                        ],
                        help_text="Assign to a display section (can be blank; use queries for dynamic)",
                        max_length=50,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Highlight as featured (e.g., in Sweet Deals)",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="e.g., Lagos, Abuja", max_length=100
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Car image - will be auto-optimized",
                        upload_to="cars/%Y/%m/%d/",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="SEO: Description of the image",
                        max_length=200,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display (lower first)"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Image",
                "verbose_name_plural": "Car Images",
                "ordering": ["order", "-is_primary", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CarInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contacted", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Car Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="cars.category",
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["make", "model"], name="cars_car_make_3ceb9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["condition", "price"], name="cars_car_conditi_da4397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["featured", "-created_at"], name="cars_car_feature_6748c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["section"], name="cars_car_section_22fa04_idx"),
        ),
    ]
