# Generated by Django 5.2.8 on 2025-12-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_interior",
            field=models.CharField(
                blank=True,
                help_text="Interior type, e.g., Leather, Fabric",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_type",
            field=models.CharField(
                blank=True, help_text="Engine type, e.g., V6, I4", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "Brand New"),
                    ("foreign_used", "Foreign Used"),
                    ("local_used", "Locally Used"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
