# Generated by Django 5.2.8 on 2025-12-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_car_car_interior_car_engine_type_alter_car_condition"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final negotiated price in Nigerian Naira (NGN)",
                        max_digits=12,
                    ),
                ),
                (
                    "sold_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the car was sold",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the buyer (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "buyer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Buyer's phone number (optional)",
                        max_length=20,
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        blank=True, help_text="Buyer's email (optional)", max_length=254
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the sale, negotiation details, etc.",
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Profit made on this sale (calculated automatically if listing price is available)",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sold Car Record",
                "verbose_name_plural": "Sold Cars Records",
                "ordering": ["-sold_date"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="is_sold",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Mark this car as sold (will show blur effect on frontend)",
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["is_sold"], name="cars_car_is_sold_46e53f_idx"),
        ),
        migrations.AddField(
            model_name="soldcar",
            name="car",
            field=models.OneToOneField(
                help_text="Select the car that was sold",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_record",
                to="cars.car",
            ),
        ),
    ]
