# Generated by Django 5.2.8 on 2025-12-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_soldcar_car_is_sold_car_cars_car_is_sold_46e53f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carinquiry",
            name="converted_to_booking",
            field=models.BooleanField(
                default=False,
                help_text="True if this inquiry was converted to a booking",
            ),
        ),
        migrations.CreateModel(
            name="CarBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_phone", models.CharField(db_index=True, max_length=20)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interest_shown", "1️⃣ Interest Shown"),
                            ("inspection_scheduled", "2️⃣ Inspection Scheduled"),
                            ("payment_scheduled", "3️⃣ Payment Scheduled"),
                            ("payment_confirmed", "4️⃣ Payment Confirmed"),
                            ("completed", "✅ Completed"),
                            ("cancelled", "❌ Cancelled"),
                        ],
                        db_index=True,
                        default="interest_shown",
                        max_length=30,
                    ),
                ),
                ("inspection_date", models.DateTimeField(blank=True, null=True)),
                ("inspection_location", models.CharField(blank=True, max_length=200)),
                (
                    "inspection_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes after inspection"
                    ),
                ),
                ("payment_scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash Payment"),
                            ("bank_draft", "Bank Draft"),
                            ("pos", "POS Payment"),
                        ],
                        max_length=100,
                    ),
                ),
                ("payment_confirmed_date", models.DateTimeField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=200)),
                (
                    "negotiated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final negotiated price (if different from listing)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("free_gift_claimed", models.BooleanField(default=False)),
                ("free_gift_claimed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_customer_message", models.DateTimeField(blank=True, null=True)),
                ("last_admin_response", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notify_by_email", models.BooleanField(default=True)),
                (
                    "car",
                    models.ForeignKey(
                        help_text="The car being booked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="cars.car",
                    ),
                ),
                (
                    "inquiry",
                    models.OneToOneField(
                        blank=True,
                        help_text="Original inquiry that led to this booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking",
                        to="cars.carinquiry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Booking",
                "verbose_name_plural": "Car Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "is_from_admin",
                    models.BooleanField(
                        default=False,
                        help_text="True if sent by admin, False if sent by customer",
                    ),
                ),
                (
                    "price_offer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price offer included in this message",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="booking_attachments/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="cars.carbooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Message",
                "verbose_name_plural": "Booking Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Changed"),
                            ("message", "Message Sent"),
                            ("inspection", "Inspection Related"),
                            ("payment", "Payment Related"),
                            ("note", "Note Added"),
                        ],
                        default="note",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.CharField(
                        default="System",
                        help_text="Who performed this action (Customer, Admin, System)",
                        max_length=100,
                    ),
                ),
                (
                    "is_visible_to_customer",
                    models.BooleanField(
                        default=True,
                        help_text="Show this activity to customer in timeline",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="cars.carbooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Activity",
                "verbose_name_plural": "Booking Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="carbooking",
            index=models.Index(
                fields=["car", "status", "is_active"],
                name="cars_carboo_car_id_f2530f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carbooking",
            index=models.Index(
                fields=["customer_phone"], name="cars_carboo_custome_f7ba60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbooking",
            index=models.Index(
                fields=["status", "-updated_at"], name="cars_carboo_status_34bd10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingmessage",
            index=models.Index(
                fields=["booking", "-created_at"], name="cars_bookin_booking_430cdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingmessage",
            index=models.Index(
                fields=["is_from_admin", "is_read"],
                name="cars_bookin_is_from_f28a39_idx",
            ),
        ),
    ]
